spring:
  application:
    name: People and Organizations Endpoint Graphql
  graphql:
    tools:
      schema-location-pattern: "**/*.graphqls"
    schema:
      printer:
        enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    ROOT: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.data.repository: DEBUG
    org.springframework.graphql.data: DEBUG
    org.hibernate: DEBUG
