spring:
  application:
    name: People and Organizations Endpoint Graphql
  graphql:
    schema:
      printer:
        enabled: true

# Common configuration shared between all profiles
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
