# Generated by Django 2.1 on 2018-09-03 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('party', '0002_auto_20180903_1635'),
	]

	operations = [
		migrations.AddField(
			model_name='contactmechanismtogeographicboundary',
			name='from_date',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='contactmechanismtogeographicboundary',
			name='thru_date',
			field=models.DateTimeField(blank=True, null=True),
		),
	]
