// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Node interface {
	IsNode()
	GetID() string
}

type Mutation struct {
}

type NewParty struct {
	PartyTypeID string  `json:"partyTypeId"`
	Comment     *string `json:"comment,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PageInfoInput struct {
	PageNumber    *int           `json:"pageNumber,omitempty"`
	PageSize      *int           `json:"pageSize,omitempty"`
	SortDirection *SortDirection `json:"sortDirection,omitempty"`
}

type Party struct {
	ID        string     `json:"id"`
	PartyType *PartyType `json:"partyType"`
	Comment   *string    `json:"comment,omitempty"`
}

func (Party) IsNode()            {}
func (this Party) GetID() string { return this.ID }

type PartyConnection struct {
	Edges    []*PartyEdge `json:"edges,omitempty"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type PartyEdge struct {
	Cursor string `json:"cursor"`
	Node   *Party `json:"node"`
}

type PartyType struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

type Query struct {
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
