# Generated by Django 2.1 on 2018-08-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20180803_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrelationship',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prioritytype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.PriorityType'),
        ),
    ]
