# Generated by Django 2.1 on 2018-08-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20180803_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ClassificationType'),
        ),
    ]
