# Generated by Django 2.1 on 2018-08-09 13:07

import uuid

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Case')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.Party')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRoleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CaseRoleType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStatusType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CaseStatusType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('case',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.Case')),
                ('contact_mechanism_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.ContactMechanismType')),
                ('party_relationship',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.PartyRelationship')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEventPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEventPurposeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CommunicationEventPurposeType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationEventRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.CommunicationEvent')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.Party')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEventRoleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CommunicationEventRoleType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationEventStatusType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CommunicationEventStatusType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='communication.CommunicationEventType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidContactMechanismRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_event_role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                                    to='communication.CommunicationEventRoleType')),
                ('contact_mechanism_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.ContactMechanismType')),
            ],
        ),
        migrations.AddField(
            model_name='communicationeventrole',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='communication.CommunicationEventRoleType'),
        ),
        migrations.AddField(
            model_name='communicationeventpurpose',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='communication.CommunicationEventPurposeType'),
        ),
        migrations.AddField(
            model_name='communicationevent',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='communication.CommunicationEventStatusType'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communication.CaseStatusType'),
        ),
    ]
