package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/erpmicroservices/people-and-organizations-endpoint-graphql/graph"
	"github.com/erpmicroservices/people-and-organizations-endpoint-graphql/internal/model"
	"github.com/erpmicroservices/people-and-organizations-endpoint-graphql/internal/service"
)

// PartyCreate is the resolver for the partyCreate field.
func (r *mutationResolver) PartyCreate(ctx context.Context, newParty model.NewParty) (*model.Party, error) {
	repo := service.NewPartyRepository(r.DB)
	return repo.CreateParty(ctx, newParty)
}

// Parties is the resolver for the parties field.
func (r *queryResolver) Parties(ctx context.Context, pageInfo model.PageInfoInput) (*model.PartyConnection, error) {
	repo := service.NewPartyRepository(r.DB)
	return repo.GetAllParties(ctx, pageInfo)
}

// Party is the resolver for the party field.
func (r *queryResolver) Party(ctx context.Context, id string) (*model.Party, error) {
	repo := service.NewPartyRepository(r.DB)
	return repo.GetPartyByID(ctx, id)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
